/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as OperaIndexRouteImport } from './routes/opera/index'
import { Route as PowerbiIaIndexRouteImport } from './routes/powerbi-ia/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const OperaIndexRoute = OperaIndexRouteImport.update({
  id: '/opera/',
  path: '/opera/',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerbiIaIndexRoute = PowerbiIaIndexRouteImport.update({
  id: '/powerbi-ia/',
  path: '/powerbi-ia/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/opera/': typeof OperaIndexRoute
  '/powerbi-ia/': typeof PowerbiIaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/opera': typeof OperaIndexRoute
  '/powerbi-ia': typeof PowerbiIaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/opera/': typeof OperaIndexRoute
  '/powerbi-ia/': typeof PowerbiIaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/opera/' | '/powerbi-ia/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/opera' | '/powerbi-ia'
  id: '__root__' | '/' | '/contacto' | '/opera/' | '/powerbi-ia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  OperaIndexRoute: typeof OperaIndexRoute
  PowerbiIaIndexRoute: typeof PowerbiIaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opera/': {
      id: '/opera/'
      path: '/opera'
      fullPath: '/opera/'
      preLoaderRoute: typeof OperaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powerbi-ia/': {
      id: '/powerbi-ia/'
      path: '/powerbi-ia'
      fullPath: '/powerbi-ia/'
      preLoaderRoute: typeof PowerbiIaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  OperaIndexRoute: OperaIndexRoute,
  PowerbiIaIndexRoute: PowerbiIaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
